# Supabase Configuration

# Project ID
project_id = "rcwjzrfpmbgxwkgzqoqo"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a view, table, or stored procedure
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use
major_version = 17

[studio]
# Port to use for Supabase Studio
port = 54323

[inbucket]
# Port to use for the email testing server
port = 54324

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
# The base URL of your website
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for (in seconds)
jwt_expiry = 3600
# Allow/disallow new user signups to your project
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project
enable_signup = false
# If enabled, users need to confirm their email address before signing in
enable_confirmations = false

# Edge Functions configuration
[functions.tweet-word]
verify_jwt = false
