	version: "3.9"

services:
    app:
        container_name: RepipiTwitterbotJS
        image: RepipiTwitterbotJS
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"