name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Build and push the Docker image
        run: |
          echo ${{ secrets.GH_PACKAGES }} | docker login docker.pkg.github.com -u d0vak1n --password-stdin
          docker build -t docker.pkg.github.com/d0vak1n/repipitwitterbotjs/repipi-bot:latest .
          docker push docker.pkg.github.com/d0vak1n/repipitwitterbotjs/repipi-bot:latest
