name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Build and push the Docker image
      run: |
        docker docker login --username d0vak1n ${{secrets.GH_PACKAGES}} ghcr.io
        docker build -t docker.pkg.github.com/d0vak1n/repipitwitterbotjs/repipi-bot:latest .
        docker push docker.pkg.github.com/d0vak1n/repipitwitterbotjs/repipi-bot:latest
